"""empty message

Revision ID: 23bc7679c138
Revises: 6786a0d3e348
Create Date: 2021-04-30 01:48:16.828150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23bc7679c138'
down_revision = '6786a0d3e348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_campo2_key', 'user', type_='unique')
    op.drop_constraint('user_campo3_key', 'user', type_='unique')
    op.drop_column('user', 'campo3')
    op.drop_column('user', 'campo2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('campo2', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('campo3', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_campo3_key', 'user', ['campo3'])
    op.create_unique_constraint('user_campo2_key', 'user', ['campo2'])
    # ### end Alembic commands ###
