"""empty message

Revision ID: 6786a0d3e348
Revises: e2c86ad35888
Create Date: 2021-04-30 01:47:20.548317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6786a0d3e348'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('campo1', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('campo2', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('campo3', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['campo1'])
    op.create_unique_constraint(None, 'user', ['campo3'])
    op.create_unique_constraint(None, 'user', ['campo2'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'campo3')
    op.drop_column('user', 'campo2')
    op.drop_column('user', 'campo1')
    # ### end Alembic commands ###
